"""Module: PDF Clinical Report Generator"""
from fpdf import FPDF
from datetime import datetime

class ClinicalReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 16)
        self.cell(0, 8, 'DEPARTMENT OF OBSTETRICS & GYNECOLOGY', 0, 1, 'C')
        self.set_font('Arial', 'B', 12)
        self.set_text_color(100, 100, 100)
        self.cell(0, 6, 'OBSTETRIC DOPPLER ULTRASOUND REPORT', 0, 1, 'C')
        self.ln(2)
        self.set_draw_color(0, 0, 0)
        self.line(10, 28, 200, 28)
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, 'Generated by Fetal Doppler CDSS - Protocol: RCOG Green-top Guideline No. 31', 0, 0, 'C')

def generate_pdf_report(data_to_process, metrics, staging):
    pdf = ClinicalReport()
    pdf.add_page()
    
    # 1. DEMOGRAPHICS
    pdf.set_font('Arial', 'B', 10)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(0, 6, ' PATIENT DETAILS', 1, 1, 'L', fill=True)
    pdf.set_font('Arial', 'B', 9)
    pdf.cell(30, 6, ' Patient ID:', 'L')
    pdf.set_font('Arial', '', 9)
    pdf.cell(65, 6, str(data_to_process.get('patient_id', 'N/A')))
    pdf.set_font('Arial', 'B', 9)
    pdf.cell(35, 6, 'Examination Date:')
    pdf.set_font('Arial', '', 9)
    pdf.cell(60, 6, datetime.now().strftime('%d %B %Y'), 'R', ln=True)
    pdf.set_font('Arial', 'B', 9)
    pdf.cell(30, 6, ' GA (by LMP):', 'L')
    pdf.set_font('Arial', '', 9)
    pdf.cell(65, 6, str(data_to_process.get('weeks_by_lmp', 'N/A')))
    pdf.set_font('Arial', 'B', 9)
    pdf.cell(35, 6, 'GA (by Scan):')
    pdf.set_font('Arial', '', 9)
    pdf.cell(60, 6, str(data_to_process.get('weeks_by_scan', 'N/A')), 'R', ln=True)
    pdf.set_font('Arial', 'B', 9)
    pdf.cell(30, 6, ' Assigned GA:', 'L,B')
    pdf.set_font('Arial', 'B', 9)
    pdf.cell(160, 6, f"{metrics.get('clinical_weeks', 'N/A')} Weeks", 'R,B', ln=True)
    pdf.ln(4)

    # 2. BIOMETRY
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(0, 6, ' FETAL BIOMETRY & ENVIRONMENT', 1, 1, 'L', fill=True)
    pdf.set_font('Arial', 'B', 9)
    pdf.cell(45, 6, ' EFW Centile:', 'L')
    pdf.set_font('Arial', '', 9)
    pdf.cell(50, 6, f"{data_to_process.get('efw_percentile', 'N/A')}th Centile")
    pdf.set_font('Arial', 'B', 9)
    pdf.cell(40, 6, 'Amniotic Fluid:')
    pdf.set_font('Arial', '', 9)
    pdf.cell(55, 6, str(data_to_process.get('amniotic_fluid', 'N/A')).upper(), 'R', ln=True)
    pdf.cell(190, 1, '', 'T', ln=True)
    pdf.ln(3)

    # 3. DOPPLER TABLE
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(0, 6, ' DOPPLER ULTRASOUND FINDINGS', 1, 1, 'L', fill=True)
    pdf.set_font('Arial', 'B', 9)
    pdf.cell(65, 6, ' Insonated Vessel', 1, 0, 'C')
    pdf.cell(35, 6, ' Pulsatility Index', 1, 0, 'C')
    pdf.cell(90, 6, ' Waveform / Status', 1, 1, 'C')
    
    pdf.set_font('Arial', '', 9)
    pdf.cell(65, 6, ' Umbilical Artery (UA)', 1, 0, 'L')
    pdf.cell(35, 6, str(metrics.get('ua_pi', 'N/A')), 1, 0, 'C')
    ua_flow = data_to_process.get('vessels', [{}])[0].get('flow_between_beats', 'N/A').upper()
    pdf.cell(90, 6, f"{ua_flow} END-DIASTOLIC FLOW", 1, 1, 'C')
    
    pdf.cell(65, 6, ' Middle Cerebral Artery (MCA)', 1, 0, 'L')
    pdf.cell(35, 6, str(metrics.get('mca_pi', 'N/A')), 1, 0, 'C')
    pdf.cell(90, 6, ' --', 1, 1, 'C')
    
    pdf.cell(65, 6, ' Cerebroplacental Ratio (CPR)', 1, 0, 'L')
    pdf.set_font('Arial', 'B', 9)
    pdf.cell(35, 6, str(metrics.get('cpr', 'N/A')), 1, 0, 'C')
    pdf.set_font('Arial', '', 9)
    pdf.cell(90, 6, ' (Ratio of MCA PI / UA PI)', 1, 1, 'C')
    
    pdf.cell(65, 6, ' Mean Uterine Artery PI', 1, 0, 'L')
    pdf.cell(35, 6, str(metrics.get('mean_ut_pi', 'N/A')), 1, 0, 'C')
    pdf.set_font('Arial', 'I', 8)
    pdf.cell(90, 6, ' (Limited predictive value in 3rd trimester)', 1, 1, 'C')
    pdf.ln(5)

    # 4. IMPRESSION
    action_text = staging.get('action', '')
    delivery_timing = action_text
    notes = ""
    if "NOTES:" in action_text:
        parts = action_text.split("NOTES:")
        delivery_timing = parts[0].replace("DELIVERY TIMING:", "").strip()
        notes = parts[1].strip()

    pdf.set_font('Arial', 'B', 11)
    pdf.cell(0, 7, ' CLINICAL IMPRESSION', 1, 1, 'L', fill=True)
    pdf.set_font('Arial', 'B', 12)
    if "PATHOLOGICAL" in staging.get('stage', ''): pdf.set_text_color(220, 0, 0)
    elif "ABNORMAL" in staging.get('stage', ''): pdf.set_text_color(200, 100, 0)
    elif "NORMAL" in staging.get('stage', ''): pdf.set_text_color(0, 128, 0)
        
    pdf.cell(0, 8, f"  {staging.get('stage', 'UNKNOWN').upper()}", 'L,R', 1, 'L')
    pdf.set_text_color(0, 0, 0)
    pdf.cell(190, 1, '', 'T', 1)
    pdf.ln(3)

    # 5. RECOMMENDATIONS
    pdf.set_font('Arial', 'B', 11)
    pdf.cell(0, 7, ' RECOMMENDATIONS & MANAGEMENT PLAN', 1, 1, 'L', fill=True)
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(45, 8, '  TIMING OF DELIVERY:', 'L', 0, 'L')
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(145, 8, delivery_timing.upper(), 'R', 1, 'L')
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(45, 8, '  SURVEILLANCE:', 'L', 0, 'L')
    pdf.set_font('Arial', '', 10)
    pdf.cell(145, 8, staging.get('interval', 'N/A').upper(), 'R', 1, 'L')
    
    if notes:
        pdf.set_font('Arial', 'B', 10)
        pdf.cell(190, 6, '  CLINICAL NOTES / INTERVENTIONS:', 'L,R', 1, 'L')
        pdf.set_font('Arial', '', 10)
        pdf.set_x(15)
        pdf.multi_cell(180, 5, notes, 0, 'L')
        
    pdf.cell(190, 2, '', 'L,R,B', 1)
    pdf.ln(3)

    # 6. RATIONALE
    pdf.set_font('Arial', 'I', 9)
    pdf.set_text_color(80, 80, 80)
    pdf.multi_cell(0, 5, staging.get('rule', ''))
    
    # 7. SIGNATURE
    pdf.ln(15)
    pdf.set_draw_color(0, 0, 0)
    pdf.line(140, pdf.get_y(), 190, pdf.get_y())
    pdf.set_font('Arial', '', 10)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(130)
    pdf.cell(60, 5, 'Consultant Obstetrician', 0, 1, 'C')

    return bytes(pdf.output(dest='S'))